services:
  postgres:
    image: postgres:alpine3.17
    hostname: postgres
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tspcup
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - tspcup-data:/data/postgres

volumes:
  tspcup-data: {}
